--------------------------------------------------------------------------------
-- FOBO Reconciliation GenAI Platform - region and business-date dimension layer
-- Oracle 19c. Apply after fobo_recon_ai_schema.sql.
--
-- REPLACES from v1:  RECON_SESSION, RECON_EXCEPTION, ANALYSIS_CASE
--                    (grain and partitioning both change - drop and recreate)
-- SUPERSEDES from v1: RECON_REGION (now REGION + RECON_REGION_SCOPE)
-- UNCHANGED from v1:  all CONFIG tables except RECON_REGION, all ANALYSIS
--                     child tables, all AUDIT tables
--
-- The grain question
--   RECON_SESSION is the fact table at grain (RECON, REGION, BUSINESS_DATE).
--   REGION_DAY and RECON_DAY are the two rollups over it:
--
--     REGION_DAY  = one controller's shift.   "APAC, 08 Sep, all recons"
--     RECON_DAY   = one recon owner's close.  "Cash vs nostro, 08 Sep, all regions"
--
--   Both need independent status and independent sign-off. A controller signs
--   off their region across recons. A recon owner signs off their recon across
--   regions, and cannot do so until every regional session beneath it closes.
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 1. THE TWO DIMENSIONS
--------------------------------------------------------------------------------

-- Region is a real dimension, not a check constraint. Shift windows drive the
-- SLA trigger policy: a wave must complete before SHIFT_START_LOCAL.
CREATE TABLE REGION (
  REGION_CODE           VARCHAR2(10)    PRIMARY KEY,
  REGION_NAME           VARCHAR2(60)    NOT NULL,
  IANA_TIMEZONE         VARCHAR2(60)    NOT NULL,
  SHIFT_START_LOCAL     VARCHAR2(5)     NOT NULL,   -- 'HH24:MI'
  SHIFT_END_LOCAL       VARCHAR2(5)     NOT NULL,
  SIGN_OFF_CUTOFF_LOCAL VARCHAR2(5)     NOT NULL,
  PREPARE_LEAD_MINUTES  NUMBER(5)       DEFAULT 150 NOT NULL,
  DISPLAY_SEQ           NUMBER(3)       NOT NULL,
  IS_ACTIVE             CHAR(1)         DEFAULT 'Y' NOT NULL
);

INSERT INTO REGION VALUES ('APAC' ,'Asia Pacific'  ,'Asia/Singapore'   ,'06:00','15:00','14:30',150,10,'Y');
INSERT INTO REGION VALUES ('EMEA' ,'Europe and MEA','Europe/London'    ,'07:00','17:00','16:30',150,20,'Y');
INSERT INTO REGION VALUES ('AMER' ,'Americas'      ,'America/New_York' ,'07:00','17:00','16:30',150,30,'Y');
INSERT INTO REGION VALUES ('LATAM','Latin America' ,'America/Sao_Paulo','08:00','17:00','16:30',120,40,'N');

-- Business date is a dimension, not a DATE column. Holidays differ by region, so
-- 08 Sep can be a business day in EMEA and a holiday in APAC. PRIOR_BUSINESS_DATE
-- is what makes carry-forward of unresolved breaks resolvable in one join.
CREATE TABLE BUSINESS_CALENDAR (
  CALENDAR_ID           NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REGION_CODE           VARCHAR2(10)    NOT NULL,
  BUSINESS_DATE         DATE            NOT NULL,
  IS_BUSINESS_DAY       CHAR(1)         DEFAULT 'Y' NOT NULL,
  PRIOR_BUSINESS_DATE   DATE,
  NEXT_BUSINESS_DATE    DATE,
  DAY_OF_WEEK           NUMBER(1)       NOT NULL,
  IS_MONTH_END          CHAR(1)         DEFAULT 'N' NOT NULL,
  IS_QUARTER_END        CHAR(1)         DEFAULT 'N' NOT NULL,
  IS_YEAR_END           CHAR(1)         DEFAULT 'N' NOT NULL,
  IS_FREEZE_PERIOD      CHAR(1)         DEFAULT 'N' NOT NULL,
  HOLIDAY_NAME          VARCHAR2(80),
  CONSTRAINT FK_CALENDAR_REGION FOREIGN KEY (REGION_CODE) REFERENCES REGION (REGION_CODE),
  CONSTRAINT UK_BUSINESS_CALENDAR UNIQUE (REGION_CODE, BUSINESS_DATE),
  CONSTRAINT CK_CALENDAR_BUSDAY CHECK (IS_BUSINESS_DAY IN ('Y','N'))
);

CREATE INDEX IX_CALENDAR_LOOKUP ON BUSINESS_CALENDAR (BUSINESS_DATE, IS_BUSINESS_DAY);

-- Which regions a recon actually runs in. A recon may be single-region.
CREATE TABLE RECON_REGION_SCOPE (
  SCOPE_ID              NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RECON_ID              NUMBER(19)      NOT NULL,
  REGION_CODE           VARCHAR2(10)    NOT NULL,
  REQUIRES_GLOBAL_SIGNOFF CHAR(1)       DEFAULT 'Y' NOT NULL,
  IS_ACTIVE             CHAR(1)         DEFAULT 'Y' NOT NULL,
  CONSTRAINT FK_SCOPE_RECON  FOREIGN KEY (RECON_ID)    REFERENCES RECON_DEFINITION (RECON_ID),
  CONSTRAINT FK_SCOPE_REGION FOREIGN KEY (REGION_CODE) REFERENCES REGION (REGION_CODE),
  CONSTRAINT UK_RECON_REGION_SCOPE UNIQUE (RECON_ID, REGION_CODE)
);


--------------------------------------------------------------------------------
-- 2. THE TWO ROLLUPS
--------------------------------------------------------------------------------

-- One controller shift. Created by the scheduler at PREPARE_START_UTC.
CREATE TABLE REGION_DAY (
  REGION_DAY_ID         NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REGION_CODE           VARCHAR2(10)    NOT NULL,
  BUSINESS_DATE         DATE            NOT NULL,
  DAY_STATUS            VARCHAR2(20)    DEFAULT 'SCHEDULED' NOT NULL,
  PREPARE_START_UTC     TIMESTAMP WITH TIME ZONE,
  SHIFT_START_UTC       TIMESTAMP WITH TIME ZONE,
  SIGN_OFF_CUTOFF_UTC   TIMESTAMP WITH TIME ZONE,
  RECONS_IN_SCOPE       NUMBER(5)       DEFAULT 0 NOT NULL,
  RECONS_READY          NUMBER(5)       DEFAULT 0 NOT NULL,
  RECONS_SIGNED_OFF     NUMBER(5)       DEFAULT 0 NOT NULL,
  BOOKS_TOTAL           NUMBER(9)       DEFAULT 0 NOT NULL,
  BOOKS_AUTO_POST       NUMBER(9)       DEFAULT 0 NOT NULL,
  BOOKS_OPEN            NUMBER(9)       DEFAULT 0 NOT NULL,
  BOOKS_ANALYSED        NUMBER(9)       DEFAULT 0 NOT NULL,
  CASES_READY           NUMBER(9)       DEFAULT 0 NOT NULL,
  CASES_PENDING_REVIEW  NUMBER(9)       DEFAULT 0 NOT NULL,
  CASES_ACCEPTED        NUMBER(9)       DEFAULT 0 NOT NULL,
  CASES_REJECTED        NUMBER(9)       DEFAULT 0 NOT NULL,
  CASES_CARRIED_FORWARD NUMBER(9)       DEFAULT 0 NOT NULL,
  READY_BEFORE_SHIFT    CHAR(1),
  SIGNED_OFF_TS         TIMESTAMP WITH TIME ZONE,
  SIGNED_OFF_BY         VARCHAR2(50),
  COUNTERS_REFRESHED_TS TIMESTAMP WITH TIME ZONE,
  CONSTRAINT FK_REGION_DAY_REGION FOREIGN KEY (REGION_CODE) REFERENCES REGION (REGION_CODE),
  CONSTRAINT UK_REGION_DAY UNIQUE (REGION_CODE, BUSINESS_DATE),
  CONSTRAINT CK_REGION_DAY_STATUS CHECK (DAY_STATUS IN
    ('SCHEDULED','PREPARING','PARTIAL','READY','IN_REVIEW','SIGNED_OFF','BREACHED','HOLIDAY'))
);

CREATE INDEX IX_REGION_DAY_BOARD ON REGION_DAY (BUSINESS_DATE, REGION_CODE, DAY_STATUS);

-- One recon's global close. Unlocks only when every regional session closes.
CREATE TABLE RECON_DAY (
  RECON_DAY_ID          NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RECON_ID              NUMBER(19)      NOT NULL,
  BUSINESS_DATE         DATE            NOT NULL,
  DAY_STATUS            VARCHAR2(20)    DEFAULT 'SCHEDULED' NOT NULL,
  REGIONS_IN_SCOPE      NUMBER(3)       DEFAULT 0 NOT NULL,
  REGIONS_SIGNED_OFF    NUMBER(3)       DEFAULT 0 NOT NULL,
  BOOKS_TOTAL           NUMBER(9)       DEFAULT 0 NOT NULL,
  CASES_ACCEPTED        NUMBER(9)       DEFAULT 0 NOT NULL,
  CASES_CARRIED_FORWARD NUMBER(9)       DEFAULT 0 NOT NULL,
  GLOBAL_SIGN_OFF_TS    TIMESTAMP WITH TIME ZONE,
  GLOBAL_SIGN_OFF_BY    VARCHAR2(50),
  CONSTRAINT FK_RECON_DAY_RECON FOREIGN KEY (RECON_ID) REFERENCES RECON_DEFINITION (RECON_ID),
  CONSTRAINT UK_RECON_DAY UNIQUE (RECON_ID, BUSINESS_DATE),
  CONSTRAINT CK_RECON_DAY_STATUS CHECK (DAY_STATUS IN
    ('SCHEDULED','IN_PROGRESS','AWAITING_REGIONS','SIGNED_OFF','BREACHED'))
);


--------------------------------------------------------------------------------
-- 3. RECON_SESSION AT THE INTERSECTION  (replaces v1 definition)
--------------------------------------------------------------------------------

DROP TABLE RECON_SESSION CASCADE CONSTRAINTS;

CREATE TABLE RECON_SESSION (
  SESSION_ID            NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REGION_DAY_ID         NUMBER(19)      NOT NULL,
  RECON_DAY_ID          NUMBER(19)      NOT NULL,
  RECON_ID              NUMBER(19)      NOT NULL,
  REGION_CODE           VARCHAR2(10)    NOT NULL,
  BUSINESS_DATE         DATE            NOT NULL,
  SESSION_STATUS        VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
  BOOKS_TOTAL           NUMBER(7)       DEFAULT 0 NOT NULL,
  BOOKS_AUTO_POST       NUMBER(7)       DEFAULT 0 NOT NULL,
  BOOKS_OPEN            NUMBER(7)       DEFAULT 0 NOT NULL,
  BOOKS_ANALYSED        NUMBER(7)       DEFAULT 0 NOT NULL,
  CASES_READY           NUMBER(7)       DEFAULT 0 NOT NULL,
  CASES_ACCEPTED        NUMBER(7)       DEFAULT 0 NOT NULL,
  CASES_REJECTED        NUMBER(7)       DEFAULT 0 NOT NULL,
  CASES_CARRIED_FORWARD NUMBER(7)       DEFAULT 0 NOT NULL,
  FIRST_WAVE_TS         TIMESTAMP WITH TIME ZONE,
  READY_TS              TIMESTAMP WITH TIME ZONE,
  SIGNED_OFF_TS         TIMESTAMP WITH TIME ZONE,
  SIGNED_OFF_BY         VARCHAR2(50),
  CONSTRAINT FK_SESSION_REGION_DAY FOREIGN KEY (REGION_DAY_ID) REFERENCES REGION_DAY (REGION_DAY_ID),
  CONSTRAINT FK_SESSION_RECON_DAY  FOREIGN KEY (RECON_DAY_ID)  REFERENCES RECON_DAY  (RECON_DAY_ID),
  CONSTRAINT FK_SESSION_RECON      FOREIGN KEY (RECON_ID)      REFERENCES RECON_DEFINITION (RECON_ID),
  CONSTRAINT UK_RECON_SESSION UNIQUE (RECON_ID, REGION_CODE, BUSINESS_DATE),
  CONSTRAINT CK_SESSION_STATUS CHECK (SESSION_STATUS IN
    ('PENDING','PREPARING','PARTIAL','READY','IN_REVIEW','SIGNED_OFF','FAILED','HOLIDAY'))
);

CREATE INDEX IX_SESSION_REGION_DAY ON RECON_SESSION (REGION_DAY_ID, SESSION_STATUS);
CREATE INDEX IX_SESSION_RECON_DAY  ON RECON_SESSION (RECON_DAY_ID, SESSION_STATUS);


--------------------------------------------------------------------------------
-- 4. HOT TABLES: COMPOSITE PARTITIONING ON THE TWO DIMENSIONS
--
-- REGION_CODE is denormalised onto both tables purely so Oracle can prune to a
-- subpartition. An APAC controller's queue query then reads one subpartition of
-- one monthly partition instead of scanning the interval. At 14 controllers
-- hitting these concurrently at shift start, this is the difference between a
-- sub-second board and a stalled dashboard.
--------------------------------------------------------------------------------

DROP TABLE RECON_EXCEPTION CASCADE CONSTRAINTS;

CREATE TABLE RECON_EXCEPTION (
  EXCEPTION_ID          NUMBER(19)      GENERATED ALWAYS AS IDENTITY,
  BUSINESS_DATE         DATE            NOT NULL,
  REGION_CODE           VARCHAR2(10)    NOT NULL,
  SESSION_ID            NUMBER(19)      NOT NULL,
  BOOK_ID               NUMBER(19)      NOT NULL,
  MBR_EXCEPTION_REF     VARCHAR2(80)    NOT NULL,
  BREAK_TYPE            VARCHAR2(40)    NOT NULL,
  BREAK_SIGNATURE       VARCHAR2(64)    NOT NULL,
  -- Identity of a break ACROSS dates. Hash of book + break type + source refs,
  -- deliberately excluding amount so a moving delta stays the same break.
  PERSISTENT_BREAK_KEY  VARCHAR2(64)    NOT NULL,
  FIRST_SEEN_BUS_DATE   DATE            NOT NULL,
  AGE_BUSINESS_DAYS     NUMBER(5)       DEFAULT 0 NOT NULL,
  CARRIED_FROM_EXC_ID   NUMBER(19),
  CCY                   CHAR(3)         NOT NULL,
  FO_AMOUNT             NUMBER(28,8),
  BO_AMOUNT             NUMBER(28,8),
  DELTA_AMOUNT          NUMBER(28,8)    NOT NULL,
  DELTA_BASE_AMOUNT     NUMBER(28,8),
  PRIOR_DAY_DELTA       NUMBER(28,8),
  VALUE_DATE            DATE,
  PRODUCT_CLASS         VARCHAR2(40),
  FO_SOURCE_SYSTEM      VARCHAR2(50),
  BO_SOURCE_SYSTEM      VARCHAR2(50),
  IS_MATERIAL           CHAR(1)         DEFAULT 'N' NOT NULL,
  INGESTED_TS           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RECON_EXCEPTION PRIMARY KEY (EXCEPTION_ID, BUSINESS_DATE),
  CONSTRAINT UK_RECON_EXCEPTION UNIQUE (MBR_EXCEPTION_REF, BUSINESS_DATE)
)
PARTITION BY RANGE (BUSINESS_DATE)
INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
SUBPARTITION BY LIST (REGION_CODE)
SUBPARTITION TEMPLATE (
  SUBPARTITION SP_APAC  VALUES ('APAC'),
  SUBPARTITION SP_EMEA  VALUES ('EMEA'),
  SUBPARTITION SP_AMER  VALUES ('AMER'),
  SUBPARTITION SP_OTHER VALUES (DEFAULT)
)
( PARTITION P_INIT VALUES LESS THAN (DATE '2026-01-01') );

CREATE INDEX IX_EXCEPTION_SIGNATURE ON RECON_EXCEPTION (BUSINESS_DATE, REGION_CODE, BREAK_SIGNATURE) LOCAL;
CREATE INDEX IX_EXCEPTION_SESSION   ON RECON_EXCEPTION (SESSION_ID, BOOK_ID) LOCAL;
-- Global index: aged-break lookup deliberately crosses business dates.
CREATE INDEX IX_EXCEPTION_PERSISTENT ON RECON_EXCEPTION (PERSISTENT_BREAK_KEY, BUSINESS_DATE DESC) GLOBAL;


DROP TABLE ANALYSIS_CASE CASCADE CONSTRAINTS;

CREATE TABLE ANALYSIS_CASE (
  CASE_ID               NUMBER(19)      GENERATED ALWAYS AS IDENTITY,
  BUSINESS_DATE         DATE            NOT NULL,
  REGION_CODE           VARCHAR2(10)    NOT NULL,
  SESSION_ID            NUMBER(19)      NOT NULL,
  WAVE_ID               NUMBER(19)      NOT NULL,
  CLUSTER_ID            NUMBER(19),
  EXCEPTION_ID          NUMBER(19)      NOT NULL,
  BOOK_ID               NUMBER(19)      NOT NULL,
  PLAYBOOK_ID           NUMBER(19)      NOT NULL,
  EVIDENCE_PACK_ID      NUMBER(19)      NOT NULL,
  EVIDENCE_PACK_HASH    VARCHAR2(64)    NOT NULL,
  CASE_STATUS           VARCHAR2(25)    DEFAULT 'QUEUED' NOT NULL,
  CLASSIFICATION        VARCHAR2(50),
  CONFIDENCE_SCORE      NUMBER(5,4),
  CONFIDENCE_TIER       VARCHAR2(15),
  IS_FANNED_OUT         CHAR(1)         DEFAULT 'N' NOT NULL,
  IS_AGED_BREAK         CHAR(1)         DEFAULT 'N' NOT NULL,
  PRIOR_CASE_ID         NUMBER(19),
  PRIOR_CASE_BUS_DATE   DATE,
  MODEL_ID              VARCHAR2(60),
  PROMPT_HASH           VARCHAR2(64),
  INPUT_TOKENS          NUMBER(9),
  OUTPUT_TOKENS         NUMBER(9),
  LATENCY_MS            NUMBER(9),
  NUMERIC_CHECK_STATUS  VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
  NUMERIC_CHECK_DETAIL  VARCHAR2(2000),
  SUPERSEDED_BY_CASE_ID NUMBER(19),
  TRACE_ID              VARCHAR2(64),
  CREATED_TS            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  COMPLETED_TS          TIMESTAMP WITH TIME ZONE,
  CONSTRAINT PK_ANALYSIS_CASE PRIMARY KEY (CASE_ID, BUSINESS_DATE),
  CONSTRAINT UK_ANALYSIS_CASE_IDEMPOTENT
    UNIQUE (SESSION_ID, BOOK_ID, EXCEPTION_ID, EVIDENCE_PACK_HASH, BUSINESS_DATE),
  CONSTRAINT CK_CASE_STATUS CHECK (CASE_STATUS IN
    ('QUEUED','ANALYSING','READY','NEEDS_INVESTIGATION','FAILED',
     'ACCEPTED','REJECTED','SUPERSEDED')),
  CONSTRAINT CK_CASE_CONF_TIER CHECK (CONFIDENCE_TIER IN ('HIGH','MEDIUM','LOW')),
  CONSTRAINT CK_CASE_NUMERIC CHECK (NUMERIC_CHECK_STATUS IN ('PENDING','PASSED','FAILED','SKIPPED'))
)
PARTITION BY RANGE (BUSINESS_DATE)
INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))
SUBPARTITION BY LIST (REGION_CODE)
SUBPARTITION TEMPLATE (
  SUBPARTITION SP_APAC  VALUES ('APAC'),
  SUBPARTITION SP_EMEA  VALUES ('EMEA'),
  SUBPARTITION SP_AMER  VALUES ('AMER'),
  SUBPARTITION SP_OTHER VALUES (DEFAULT)
)
( PARTITION P_INIT VALUES LESS THAN (DATE '2026-01-01') );

CREATE INDEX IX_CASE_QUEUE ON ANALYSIS_CASE
  (BUSINESS_DATE, REGION_CODE, SESSION_ID, CASE_STATUS, CONFIDENCE_TIER) LOCAL;
CREATE INDEX IX_CASE_BOOK  ON ANALYSIS_CASE (BOOK_ID, BUSINESS_DATE) LOCAL;
CREATE INDEX IX_CASE_AGED  ON ANALYSIS_CASE (IS_AGED_BREAK, BUSINESS_DATE, REGION_CODE) LOCAL;


--------------------------------------------------------------------------------
-- 5. READ MODEL FOR THE REGION x DATE BOARD
--------------------------------------------------------------------------------

-- Top of the dashboard: one row per region for the selected business date.
CREATE OR REPLACE VIEW V_REGION_DAY_BOARD AS
SELECT
  rd.REGION_DAY_ID,
  rd.REGION_CODE,
  r.REGION_NAME,
  r.IANA_TIMEZONE,
  r.SHIFT_START_LOCAL,
  r.SIGN_OFF_CUTOFF_LOCAL,
  rd.BUSINESS_DATE,
  bc.IS_BUSINESS_DAY,
  bc.IS_MONTH_END,
  bc.IS_QUARTER_END,
  bc.PRIOR_BUSINESS_DATE,
  bc.NEXT_BUSINESS_DATE,
  bc.HOLIDAY_NAME,
  rd.DAY_STATUS,
  rd.RECONS_IN_SCOPE,
  rd.RECONS_READY,
  rd.RECONS_SIGNED_OFF,
  rd.BOOKS_TOTAL,
  rd.BOOKS_AUTO_POST,
  rd.BOOKS_TOTAL - rd.BOOKS_AUTO_POST        AS BOOKS_MANUAL,
  rd.BOOKS_OPEN,
  rd.BOOKS_ANALYSED,
  rd.BOOKS_OPEN - rd.BOOKS_ANALYSED          AS BOOKS_AWAITING_ANALYSIS,
  rd.CASES_PENDING_REVIEW,
  rd.CASES_ACCEPTED,
  rd.CASES_REJECTED,
  rd.CASES_CARRIED_FORWARD,
  rd.READY_BEFORE_SHIFT,
  rd.SHIFT_START_UTC,
  rd.SIGN_OFF_CUTOFF_UTC,
  rd.SIGNED_OFF_TS,
  rd.SIGNED_OFF_BY,
  CASE WHEN rd.BOOKS_OPEN = 0 THEN 0
       ELSE ROUND(rd.BOOKS_ANALYSED / rd.BOOKS_OPEN * 100, 1) END AS PCT_ANALYSED
FROM REGION_DAY rd
JOIN REGION r           ON r.REGION_CODE = rd.REGION_CODE
LEFT JOIN BUSINESS_CALENDAR bc
       ON bc.REGION_CODE = rd.REGION_CODE
      AND bc.BUSINESS_DATE = rd.BUSINESS_DATE;


-- Drill one level: recons within the selected region and date.
CREATE OR REPLACE VIEW V_REGION_DAY_RECONS AS
SELECT
  s.SESSION_ID,
  s.REGION_DAY_ID,
  s.RECON_DAY_ID,
  s.REGION_CODE,
  s.BUSINESS_DATE,
  d.RECON_CODE,
  d.RECON_NAME,
  d.RECON_TYPE,
  s.SESSION_STATUS,
  s.BOOKS_TOTAL,
  s.BOOKS_AUTO_POST,
  s.BOOKS_OPEN,
  s.BOOKS_ANALYSED,
  s.BOOKS_OPEN - s.BOOKS_ANALYSED            AS BOOKS_AWAITING_ANALYSIS,
  s.CASES_READY - s.CASES_ACCEPTED - s.CASES_REJECTED AS CASES_PENDING_REVIEW,
  s.CASES_ACCEPTED,
  s.CASES_REJECTED,
  s.CASES_CARRIED_FORWARD,
  s.FIRST_WAVE_TS,
  s.READY_TS,
  s.SIGNED_OFF_TS,
  s.SIGNED_OFF_BY,
  rdy.REGIONS_IN_SCOPE,
  rdy.REGIONS_SIGNED_OFF,
  rdy.DAY_STATUS                             AS GLOBAL_RECON_STATUS
FROM RECON_SESSION s
JOIN RECON_DEFINITION d ON d.RECON_ID = s.RECON_ID
JOIN RECON_DAY rdy      ON rdy.RECON_DAY_ID = s.RECON_DAY_ID;


-- The recon owner's cross-region view for one business date.
CREATE OR REPLACE VIEW V_RECON_DAY_GLOBAL AS
SELECT
  rdy.RECON_DAY_ID,
  rdy.RECON_ID,
  d.RECON_CODE,
  d.RECON_NAME,
  rdy.BUSINESS_DATE,
  rdy.DAY_STATUS,
  rdy.REGIONS_IN_SCOPE,
  rdy.REGIONS_SIGNED_OFF,
  LISTAGG(s.REGION_CODE || ':' || s.SESSION_STATUS, ' ')
    WITHIN GROUP (ORDER BY s.REGION_CODE)    AS REGION_STATUS_TRAIL,
  SUM(s.BOOKS_OPEN)                          AS BOOKS_OPEN,
  SUM(s.BOOKS_ANALYSED)                      AS BOOKS_ANALYSED,
  SUM(s.CASES_ACCEPTED)                      AS CASES_ACCEPTED,
  SUM(s.CASES_CARRIED_FORWARD)               AS CASES_CARRIED_FORWARD,
  rdy.GLOBAL_SIGN_OFF_TS,
  rdy.GLOBAL_SIGN_OFF_BY
FROM RECON_DAY rdy
JOIN RECON_DEFINITION d ON d.RECON_ID = rdy.RECON_ID
LEFT JOIN RECON_SESSION s ON s.RECON_DAY_ID = rdy.RECON_DAY_ID
GROUP BY rdy.RECON_DAY_ID, rdy.RECON_ID, d.RECON_CODE, d.RECON_NAME,
         rdy.BUSINESS_DATE, rdy.DAY_STATUS, rdy.REGIONS_IN_SCOPE,
         rdy.REGIONS_SIGNED_OFF, rdy.GLOBAL_SIGN_OFF_TS, rdy.GLOBAL_SIGN_OFF_BY;


-- Breaks that survived prior business dates. Controllers triage these first.
CREATE OR REPLACE VIEW V_AGED_BREAKS AS
SELECT
  e.EXCEPTION_ID,
  e.BUSINESS_DATE,
  e.REGION_CODE,
  e.SESSION_ID,
  mb.BOOK_CODE,
  mb.BOOK_NAME,
  e.PERSISTENT_BREAK_KEY,
  e.BREAK_TYPE,
  e.BREAK_SIGNATURE,
  e.CCY,
  e.DELTA_AMOUNT,
  e.PRIOR_DAY_DELTA,
  e.DELTA_AMOUNT - NVL(e.PRIOR_DAY_DELTA, 0) AS DELTA_MOVEMENT,
  e.FIRST_SEEN_BUS_DATE,
  e.AGE_BUSINESS_DAYS,
  c.CASE_ID,
  c.CASE_STATUS,
  c.CONFIDENCE_TIER,
  c.PRIOR_CASE_ID
FROM RECON_EXCEPTION e
JOIN MASTER_BOOK mb ON mb.BOOK_ID = e.BOOK_ID
LEFT JOIN ANALYSIS_CASE c
       ON c.EXCEPTION_ID = e.EXCEPTION_ID
      AND c.BUSINESS_DATE = e.BUSINESS_DATE
      AND c.CASE_STATUS <> 'SUPERSEDED'
WHERE e.AGE_BUSINESS_DAYS > 0;


--------------------------------------------------------------------------------
-- 6. COUNTER REFRESH
-- The WebSocket gateway pushes deltas; this keeps the durable rollups honest.
-- Call after each wave completes and on every terminal case decision.
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE REFRESH_REGION_DAY_COUNTERS (
  p_region_day_id IN NUMBER
) AS
BEGIN
  MERGE INTO REGION_DAY t
  USING (
    SELECT
      s.REGION_DAY_ID,
      COUNT(*)                                      AS RECONS_IN_SCOPE,
      SUM(CASE WHEN s.SESSION_STATUS IN ('READY','IN_REVIEW','SIGNED_OFF')
               THEN 1 ELSE 0 END)                   AS RECONS_READY,
      SUM(CASE WHEN s.SESSION_STATUS = 'SIGNED_OFF' THEN 1 ELSE 0 END) AS RECONS_SIGNED_OFF,
      SUM(s.BOOKS_TOTAL)                            AS BOOKS_TOTAL,
      SUM(s.BOOKS_AUTO_POST)                        AS BOOKS_AUTO_POST,
      SUM(s.BOOKS_OPEN)                             AS BOOKS_OPEN,
      SUM(s.BOOKS_ANALYSED)                         AS BOOKS_ANALYSED,
      SUM(s.CASES_READY)                            AS CASES_READY,
      SUM(s.CASES_READY - s.CASES_ACCEPTED - s.CASES_REJECTED) AS CASES_PENDING_REVIEW,
      SUM(s.CASES_ACCEPTED)                         AS CASES_ACCEPTED,
      SUM(s.CASES_REJECTED)                         AS CASES_REJECTED,
      SUM(s.CASES_CARRIED_FORWARD)                  AS CASES_CARRIED_FORWARD
    FROM RECON_SESSION s
    WHERE s.REGION_DAY_ID = p_region_day_id
    GROUP BY s.REGION_DAY_ID
  ) src
  ON (t.REGION_DAY_ID = src.REGION_DAY_ID)
  WHEN MATCHED THEN UPDATE SET
    t.RECONS_IN_SCOPE       = src.RECONS_IN_SCOPE,
    t.RECONS_READY          = src.RECONS_READY,
    t.RECONS_SIGNED_OFF     = src.RECONS_SIGNED_OFF,
    t.BOOKS_TOTAL           = src.BOOKS_TOTAL,
    t.BOOKS_AUTO_POST       = src.BOOKS_AUTO_POST,
    t.BOOKS_OPEN            = src.BOOKS_OPEN,
    t.BOOKS_ANALYSED        = src.BOOKS_ANALYSED,
    t.CASES_READY           = src.CASES_READY,
    t.CASES_PENDING_REVIEW  = src.CASES_PENDING_REVIEW,
    t.CASES_ACCEPTED        = src.CASES_ACCEPTED,
    t.CASES_REJECTED        = src.CASES_REJECTED,
    t.CASES_CARRIED_FORWARD = src.CASES_CARRIED_FORWARD,
    t.DAY_STATUS = CASE
      WHEN src.RECONS_SIGNED_OFF = src.RECONS_IN_SCOPE THEN 'SIGNED_OFF'
      WHEN src.RECONS_READY      = src.RECONS_IN_SCOPE THEN 'READY'
      WHEN src.RECONS_READY > 0                        THEN 'PARTIAL'
      ELSE t.DAY_STATUS END,
    t.READY_BEFORE_SHIFT = CASE
      WHEN t.READY_BEFORE_SHIFT IS NOT NULL THEN t.READY_BEFORE_SHIFT
      WHEN src.RECONS_READY = src.RECONS_IN_SCOPE
       AND SYSTIMESTAMP <= t.SHIFT_START_UTC THEN 'Y'
      WHEN src.RECONS_READY = src.RECONS_IN_SCOPE THEN 'N'
      ELSE NULL END,
    t.COUNTERS_REFRESHED_TS = SYSTIMESTAMP;
END REFRESH_REGION_DAY_COUNTERS;
/


-- Carry unresolved breaks into the next business date. Run at session open.
CREATE OR REPLACE PROCEDURE CARRY_FORWARD_BREAKS (
  p_session_id IN NUMBER
) AS
  v_region   VARCHAR2(10);
  v_bus_date DATE;
  v_prior    DATE;
BEGIN
  SELECT REGION_CODE, BUSINESS_DATE INTO v_region, v_bus_date
  FROM RECON_SESSION WHERE SESSION_ID = p_session_id;

  SELECT PRIOR_BUSINESS_DATE INTO v_prior
  FROM BUSINESS_CALENDAR
  WHERE REGION_CODE = v_region AND BUSINESS_DATE = v_bus_date;

  UPDATE RECON_EXCEPTION e
     SET (e.FIRST_SEEN_BUS_DATE, e.AGE_BUSINESS_DAYS,
          e.CARRIED_FROM_EXC_ID, e.PRIOR_DAY_DELTA) = (
       SELECT p.FIRST_SEEN_BUS_DATE, p.AGE_BUSINESS_DAYS + 1,
              p.EXCEPTION_ID, p.DELTA_AMOUNT
       FROM RECON_EXCEPTION p
       WHERE p.PERSISTENT_BREAK_KEY = e.PERSISTENT_BREAK_KEY
         AND p.BUSINESS_DATE = v_prior
         AND p.REGION_CODE = v_region
         AND ROWNUM = 1)
   WHERE e.SESSION_ID = p_session_id
     AND EXISTS (
       SELECT 1 FROM RECON_EXCEPTION p
       WHERE p.PERSISTENT_BREAK_KEY = e.PERSISTENT_BREAK_KEY
         AND p.BUSINESS_DATE = v_prior
         AND p.REGION_CODE = v_region);

  UPDATE RECON_SESSION
     SET CASES_CARRIED_FORWARD = (
       SELECT COUNT(*) FROM RECON_EXCEPTION
       WHERE SESSION_ID = p_session_id AND AGE_BUSINESS_DAYS > 0)
   WHERE SESSION_ID = p_session_id;
END CARRY_FORWARD_BREAKS;
/
